#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#
menuentry "Gentoo LiveCD from ISO" {
    set isofile="/boot/ISO/gentoo-custom.iso"
    insmod loopback
    insmod iso9660
    insmod part_gpt
    insmod fat
    search --no-floppy --set=root --file $isofile
    loopback loop $isofile
    linux (loop)/boot/gentoo root=/dev/ram0 loop=$isofile cdroot
    initrd (loop)/boot/gentoo.igz
}

